### ISSUE TITLE
renesas-ra: Not display board images on DOWNLOAD Web site.

### ISSUE THREAD

**Issue by TakeoTakahashi2020** [micropython/micropython-media#45]
Hello,

I changed folder name for EK-RA* board on #44.
However, the board image is not displayed correctly on https://micropython.org/download/?port=renesas-ra as below:
What should I do to solve this issue?

![image](https://github.com/micropython/micropython-media/assets/74999249/b7459a8c-9ccf-4d23-8ef0-b922ca5f7849)

**Comment by dpgeorge** [comment]
Sorry, the server that holds these images was not updated with the latest changes.

It has been fixed now.

Please check, and close this issue if it now works for you, thanks!

**Comment by TakeoTakahashi2020** [comment]
Thank you @dpgeorge san.  I have confirmed that it works.   I will close this issue.

**Comment by dpgeorge** [comment]
Very good, thank you!
