### ISSUE TITLE
Pull requests are going stale

### ISSUE THREAD

**Issue by gitcnd** [micropython/micropython-media#59]
There's 18 contributions sitting in the queue.

If you don't want anyone to help - put up a notice so we know not to waste our time.

**Comment by projectgus** [comment]
I understand that you're feeling frustrated about the state of your PR, but opening issues are not productive.

Please refer to these other replies:
* https://github.com/micropython/micropython/issues/13432#issuecomment-1892849445
* https://github.com/micropython/micropython/pull/13253#issuecomment-1892856790
